<?php

require('CreatePayment.php');

$payerID = $_GET['payerID'];
echo $payerID;
$urlExec = $_GET['url.links[2].href'];
echo $urlExec;
//echo $url;

// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, $urlExec);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'PATCH');

curl_setopt($ch, CURLOPT_POSTFIELDS, "{\n\n  {\n\n    \"op\": \"replace\",\n\n    \"path\": \"/transactions/0/amount\",\n\n    \"value\": {\n\n      \"total\": \"25.00\",\n\n      \"currency\": \" BRL \",\n\n      \"details\": {\n\n        \"subtotal\": \"20.00\",\n\n        \"shipping\": \"5.00\"\n\n      }\n\n    }\n\n  }, {\n\n    \"op\": \"add\",\n\n    \"path\": \"/transactions/0/item_list/shipping_address\",\n\n    \"value\": {\n\n      \"recipient_name\": \"Max Santos\",\n\n      \"line1\": \"Greg?rio Rolim de Oliveira, 42\",\n\n      \"city\": \"Votorantim\",\n\n      \"postal_code\": \"18117-134\",\n\n      \"country_code\": \"BR\"\n\n    }\n\n  }\n\n}");

$headers = array();
$headers[] = 'Content-Type: application/json';
$headers[] = 'Authorization: Bearer'. $atoken;
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$result = curl_exec($ch);

if (curl_errno($ch)) {
    echo 'Error:' . curl_error($ch);
}
curl_close($ch);

?>